name: Noodling

on:
  push:
  pull_request:

jobs:
  noodle:
    name: Noodle
    runs-on: ubuntu-latest
#    container: ghcr.io/zephyrproject-rtos/ci:latest

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: other stuff
      run: |
        sudo apt update
        sudo apt install doxygen graphviz
